// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuGz0c7FOcSBPI2i3Zs3MqybZ5-0TwbVM',
    appId: '1:876045336744:web:89e94a0d9e2d3b2976029d',
    messagingSenderId: '876045336744',
    projectId: 'learn-sphere-59b7f',
    authDomain: 'learn-sphere-59b7f.firebaseapp.com',
    storageBucket: 'learn-sphere-59b7f.firebasestorage.app',
    measurementId: 'G-P8E2ZE5F1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJnDXRqFYsrrgejQ7tZhPXUINuNb56moY',
    appId: '1:876045336744:android:e4ce0b45fb3e0b7276029d',
    messagingSenderId: '876045336744',
    projectId: 'learn-sphere-59b7f',
    storageBucket: 'learn-sphere-59b7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDw102CB2M_KNGIa7j9h8DOAbpn_eKa6w',
    appId: '1:876045336744:ios:3cbc55f07013c6bb76029d',
    messagingSenderId: '876045336744',
    projectId: 'learn-sphere-59b7f',
    storageBucket: 'learn-sphere-59b7f.firebasestorage.app',
    iosBundleId: 'com.example.excelerate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDw102CB2M_KNGIa7j9h8DOAbpn_eKa6w',
    appId: '1:876045336744:ios:3cbc55f07013c6bb76029d',
    messagingSenderId: '876045336744',
    projectId: 'learn-sphere-59b7f',
    storageBucket: 'learn-sphere-59b7f.firebasestorage.app',
    iosBundleId: 'com.example.excelerate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuGz0c7FOcSBPI2i3Zs3MqybZ5-0TwbVM',
    appId: '1:876045336744:web:2806903b0be6050a76029d',
    messagingSenderId: '876045336744',
    projectId: 'learn-sphere-59b7f',
    authDomain: 'learn-sphere-59b7f.firebaseapp.com',
    storageBucket: 'learn-sphere-59b7f.firebasestorage.app',
    measurementId: 'G-179LKJ2SSD',
  );
}
